name: Run Postman Tests

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: '0 3 * * *'  # Runs at 3 AM UTC daily (adjust as needed)
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run Postman Test Collection with HTML Report
        run: |
          newman run "PostmanSample/SampleAPITests.postman_collection.json" --reporters cli,html --reporter-html-export report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: postman-test-report
          path: report.html
